name: Markdown Lint

on:
  push:
    paths:
      - '**/*.md'

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run markdownlint
        uses: avto-dev/markdown-lint@v1
        continue-on-error: true
