name: Update Random GIF in README

on:
  push:

jobs:
  update-gif:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pick a random GIF
        id: pickgif
        run: |
          mapfile -t gifs < gifs.txt
          RANDOM_GIF=${gifs[$RANDOM % ${#gifs[@]}]}
          echo "gif_url=$RANDOM_GIF" >> $GITHUB_OUTPUT

      - name: Replace the GIF in README
        run: |
          sed -i -E 's|!\[Random GIF\]\(.*\)|![Random GIF]('"${{ steps.pickgif.outputs.gif_url }}"')|' README.md

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git diff --quiet || (git commit -am "🔁 Update random GIF" && git push)
