name: Update README with Random GIF

on:
  push:

jobs:
  gif-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Pick Random GIF
        id: gif
        run: |
          mapfile -t gifs < gifs.txt
          RANDOM_GIF=${gifs[$RANDOM % ${#gifs[@]}]}
          echo "gif_url=$RANDOM_GIF" >> "$GITHUB_OUTPUT"

      - name: Replace GIF in README
        run: |
          sed -i -E 's|!\[Random GIF\]\(.*\)|![Random GIF]('"${{ steps.gif.outputs.gif_url }}"')|' README.md

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "🔄 Updated GIF in README"
          git push
